### ISSUE TITLE
Suggestion: moving the solution to a solution branch 

### ISSUE THREAD

**Issue by zurda** [foundersandcoders/ws-pure-functions-easy-testing#11]
Since this is a week 2 workshop, and just in case the temptation to look might be too big (we want students to struggle) - we might consider moving the solution to a solution branch.
cc: @astroash @eliascodes @m4v15 @shiryz

**Comment by astroash** [comment]
Historically we have moved away from using solution branches as they often get forgotten about and are more difficult to demonstrate solutions with eg as a mentor doing a live coding demo it is easy to peak in a folder than it is to switch branches. 

I like to trust that students will have the self determination to use 20:20:20 rather than cheat if this is properly introduced to them.

**Comment by zurda** [comment]
Thanks for clarifying Ash! 
This approach makes sense. For some reason I thought this particular ws is the exception in having the solution in the master branch. It's the first time seeing the solution in master for me, but I guess I just didn't notice it in others because I wasn't mentoring it :) Oops. 

Closing the issue :)
